Assignment 3 - Automated Latin Square: file.h File Reference
file.h File Reference
Header file for reading and managing a Latin square.
#include <stdio.h>
#include <stdlib.h>
Macros
#define N 9
Maximum size of the Latin square.
Functions
void free2DArray (int **array, int size)
Frees a dynamically allocated 2D array.
int ** readLatinSquare (const char *filename, int *size)
Reads a Latin square from a file.
Detailed Description
Header file for reading and managing a Latin square.
Provides utility functions to read a Latin square from a file and manage memory for 2D integer arrays.
This file contains function declarations for reading a Latin square from a file and freeing a dynamically allocated 2D array used to store the Latin square data.
Authors
Panagiotis Tsembekis
Rafael Tsekouronas
Bug:
No known bugs.
This file includes functions to dynamically allocate, read, and deallocate memory for a 2D array representing a Latin square. The main functionalities are:
Reading a Latin square from a file.
Safely freeing the memory allocated for a 2D array.
The functions in this file ensure robust error handling for file operations and memory allocation.
Authors
Panagiotis Tsembekis
Rafael Tsekouronas
Bug:
No known bugs.
Macro Definition Documentation
N
#define N 9
Maximum size of the Latin square.
Function Documentation
free2DArray()
void free2DArray (int ** array, int size)
Frees a dynamically allocated 2D array.
This function deallocates memory for a 2D array of integers. It is assumed that each row of the array was dynamically allocated separately.
Parameters
array A pointer to the 2D array to be freed.
size The number of rows in the array.
{
    if (array != NULL) {
        for (int i = 0; i < size; i++) {
            free(array[i]); // free each column
        }
        free(array); // free every row
    }
}
Referenced by freeNode(), initNode(), main(), and readLatinSquare().
readLatinSquare()
int ** readLatinSquare (const char * filename, int * size)
Reads a Latin square from a file.
This function reads a Latin square from a given file. The file should contain the size of the square (as the first integer) followed by the elements of the square in row-major order. If an error occurs, such as invalid size or memory allocation failure, the function returns NULL.
Parameters
filename The name of the file containing the Latin square.
size A pointer to an integer where the function will store the size of the Latin square upon successful read.
Returns
A dynamically allocated 2D array representing the Latin square, or NULL if an error occurs.
{
    // Open file for reading
    FILE *fp = fopen(filename, "r");
    // Check file pointer after attempting to open file
    if (fp == NULL)
    {
        perror("Error occurred while attempting to read from file.\n");
        return NULL;
    }
    // Check n (size of latin square)
    if (fscanf(fp, "%d", size) != 1 || *size <= 0 || *size > N) // check fscanf return code and size's value
    {
        perror("Invalid size of Latin Square!\n");
        fclose(fp);
        return NULL; // close file and exit
    }
    // Allocate memory for 2D array
    int **array = (int **)malloc(*size * sizeof(int *));
    if (array == NULL) // check for incorrect memory allocation for rows
    {
        perror("Memory allocation for rows of 2D array failed.\n");
        fclose(fp);
        return NULL;
    }
    for (int i = 0; i < *size; i++) // allocate memory for columns
    {
        array[i] = (int *)malloc(*size * sizeof(int));
        if (array[i] == NULL) // check for incorrect memory allocation for columns
        {
            perror("Memory allocation failed for columns.\n");
            free2DArray(array, i); // free previously allocated rows
            fclose(fp);
            return NULL;
        }
    }
    // Read initial latin square values from file
    for (int i = 0; i < *size; i++)
    {
        for (int j = 0; j < *size; j++)
        {
            if (fscanf(fp, "%d", &array[i][j]) != 1) // if read more than 1 argument => incorrect
            {
                perror("Error reading data from file.\n");
                free2DArray(array, *size); // free allocated space for array
                fclose(fp);
                return NULL;
            }
        }
    }
    fclose(fp);
    return array;
}
References free2DArray(), and N.
Referenced by main().