Assignment 3 - Automated Latin Square: solver.c File Reference
solver.c File Reference
Implementation of the Latin square puzzle-solving algorithm using backtracking and a stack.
#include "solver.h"
#include <string.h>
Functions
bool attemptPlacement (STACK *stack, int **square, int size, int *numPush, int *stepsNum, int *rowIndex, int *colIndex, int *triedNumbers, int startIndex)
Attempts to place a number in the next empty cell of the Latin square.
bool puzzleSolver (STACK *stack, int **square, int size, int *numPush, int *numPop)
Solves the Latin square puzzle using backtracking.
bool isSafe (int **square, int row, int col, int num, int size)
Checks if placing a number at the given row and column is valid in the current Latin square.
bool findEmptyPosition (int **square, int size, int *row, int *col)
Finds the next empty position in the Latin square.
Detailed Description
Implementation of the Latin square puzzle-solving algorithm using backtracking and a stack.
This file contains functions that attempt to solve a Latin square puzzle by placing numbers while checking each move against the rules of the puzzle. It uses backtracking with a stack to keep track of placements and to revert to previous states when necessary.
The main functions include puzzleSolver to drive the solving process, attemptPlacement to place numbers while following constraints, and helper functions isSafe and findEmptyPosition to assist in validating placements and locating empty positions.
Authors
Panagiotis Tsembekis
Rafael Tsekouronas
Bug:
No known bugs.
Function Documentation
attemptPlacement()
bool attemptPlacement (STACK * stack, int ** square, int size, int * numPush, int * stepsNum, int * rowIndex, int * colIndex, int * triedNumbers, int startIndex)
Attempts to place a number in the next empty cell of the Latin square.
This function acts as a helper function for puzzleSolver. It tries to place numbers sequentially in the specified cell, skipping those that have already been tried. If a valid placement is found, it pushes the state onto the stack.
Parameters
stack The stack used for storing states of the puzzle.
square The current state of the Latin square as a 2D array.
size The size of the Latin square.
numPush Pointer to the counter tracking the number of pushes to the stack.
stepsNum Pointer to the counter tracking the total steps taken.
rowIndex Pointer to the current row being processed.
colIndex Pointer to the current column being processed.
triedNumbers Array indicating numbers that have already been attempted for the current cell.
startIndex The starting number to attempt placement.
Returns
true if a placement was successful, false otherwise.
See also
puzzleSolver(STACK *stack, int **square, int size, int *numPush, int *numPop) For the main function that calls this helper.
{
    for (int i = startIndex; i <= size; i++) // begin from number given at `startingIndex`
    {
        if (triedNumbers[i] == 1)
            continue; // skip numbers that have been tried
        if (isSafe(square, *rowIndex, *colIndex, i, size)) // check if number adheres to rules of the game
        {
            // Initialize a new node for the new current state
            NODE *node;
            if (initNode(&node, square, *rowIndex, *colIndex, size) == EXIT_FAILURE)
            {
                return false; // handle memory allocation failure
            }
            // Insert the new value
            node->row = *rowIndex;
            node->col = *colIndex;
            node->square[*rowIndex][*colIndex] = i;
            // Push the new state onto the stack
            printf("PUSH: STEP %d\n", *stepsNum);
            push(stack, node);
            printNode(stack->top);
            (*numPush)++;
            (*stepsNum)++;
            // Update `square` by modifying its contents (no need to change `square` itself)
            for (int i = 0; i < size; i++)
            {
                memcpy(square[i], node->square[i], size * sizeof(int)); // copy row of `square` to the node's square array
            }
            memset(triedNumbers, 0, (size + 1) * sizeof(int)); // reset tried numbers for next function call
            return true; // successfull placement
        }
        else // not safe insertion
        {
            triedNumbers[i] = 1; // mark this number as tried
        }
    }
    return false; // no placement was possible
}
References node::col, initNode(), isSafe(), printNode(), push(), node::row, node::square, and stack::top.
Referenced by puzzleSolver().
findEmptyPosition()
bool findEmptyPosition (int ** square, int size, int * row, int * col)
Finds the next empty position in the Latin square.
Parameters
square The current state of the Latin square as a 2D array.
size The size of the Latin square (n x n).
row Pointer to store the row of the next empty position.
col Pointer to store the column of the next empty position.
Returns
true if an empty position is found, false if the Latin square is complete.
{
    // Iterate through the whole array
    for (int i = 0; i < size; i++)
    {
        for (int j = 0; j < size; j++)
        {
            if (square[i][j] == 0) // =0 indicates empty cell
            {
                // Set values for row and column and return true
                *row = i;
                *col = j;
                return true;
            }
        }
    }
    return false; // if condition is reached -> solved! :)
}
Referenced by puzzleSolver().
isSafe()
bool isSafe (int ** square, int row, int col, int num, int size)
Checks if placing a number at the given row and column is valid in the current Latin square.
Parameters
square The current state of the Latin square as a 2D array.
row The row in which the number is to be placed.
col The column in which the number is to be placed.
num The number to check.
size The size of the Latin square (n x n).
Returns
true if placing the number does not violate any rules, false otherwise.
{
    // Step 1: Check row condition - One element 'num' per row
    for (int j = 0; j < size; j++)
    {
        if (abs(square[row][j]) == num) // handle both positive and negative (pre-given) values
        {
            printf("\nError: Illegal value insertion! | Can't insert %d at (%d,%d).\n", num, row, col);
            return false;
        }
    }
    // Step 2: Check column condition - One element 'num' per column
    for (int i = 0; i < size; i++)
    {
        if (abs(square[i][col]) == num) // handle both positive and negative (pre-given) values
        {
            printf("\nError: Illegal value insertion! | Can't insert %d at (%d,%d).\n", num, row, col);
            return false;
        }
    }
    return true;
}
Referenced by attemptPlacement().
puzzleSolver()
bool puzzleSolver (STACK * stack, int ** square, int size, int * numPush, int * numPop)
Solves the Latin square puzzle using backtracking.
Attempts to solve the Latin square by placing numbers in empty cells while adhering to row and column uniqueness rules. If no valid placement is possible, it backtracks by reverting to previous states in the stack.
Parameters
stack A stack used to store puzzle states for backtracking.
square The Latin square to be solved as a 2D array.
size The size of the Latin square (n x n).
numPush Pointer to an integer tracking the number of pushes to the stack.
numPop Pointer to an integer tracking the number of pops from the stack.
Returns
true if the puzzle is solved, false if no solution exists.
{
    int stepsNum = 1, rowIndex = -1, colIndex = -1;
    int *triedNumbers = (int *)calloc(size + 1, sizeof(int)); // dynamic array initialized to 0
    while (findEmptyPosition(square, size, &rowIndex, &colIndex)) // while `square` is not filled
    {
        // Attempt placemenet
        bool placed = attemptPlacement(stack, square, size, numPush, &stepsNum, &rowIndex, &colIndex, triedNumbers, 1);
        if (!placed) // if no number [1,size] managed to be inserted, we need to backtrack
        {
            while (!placed) // backtrack until we can insert a new number
            {
                if (isEmpty(stack)) // if empty stack is reached, we have no possible solution
                {
                    free(triedNumbers);
                    return false; // no solution exists
                }
                // Print and pop current state
                printf("POP: STEP %d\n", stepsNum);
                printNode(stack->top);
                NODE *poppedNode = pop(stack);
                // Retrieve index and value of last inserted number
                rowIndex = poppedNode->row;
                colIndex = poppedNode->col;
                int lastNumTried = poppedNode->square[rowIndex][colIndex];
                square[rowIndex][colIndex] = 0; // reset the cell
                freeNode(poppedNode); // free last state
                stepsNum++;
                (*numPop)++;
                // Reset `triedNumbers` and mark `lastNumTried` as tried
                memset(triedNumbers, 0, (size + 1) * sizeof(int));
                triedNumbers[lastNumTried] = 1;
                // Attempt to place the next number starting from `lastNumTried + 1`
                placed = attemptPlacement(stack, square, size, numPush, &stepsNum, &rowIndex, &colIndex, triedNumbers, lastNumTried + 1);
            }
        }
    }
    free(triedNumbers);
    return true;
}
References attemptPlacement(), findEmptyPosition(), freeNode(), isEmpty(), pop(), printNode(), and stack::top.
Referenced by main().