Assignment 3 - Automated Latin Square: stack.h File Reference
stack.h File Reference
Header file for stack operations involving nodes containing a Latin square board.
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
Data Structures
struct node
struct stack
Typedefs
typedef struct node NODE
typedef struct stack STACK
Functions
int initStack (STACK **stack)
Initializes the stack.
int initNode (NODE **newNode, int **square, int row, int col, int size)
Initializes a new node with a Latin square board and position.
int push (STACK *stack, NODE *newNode)
Pushes a node onto the stack.
NODE * pop (STACK *stack)
Pops a node from the stack.
bool isEmpty (STACK *stack)
Checks if the stack is empty.
void printNode (NODE *node)
Prints the contents of a node.
void printStack (STACK *stack, int size)
Prints the entire stack from top to bottom.
void freeNode (NODE *node)
Frees memory allocated for a node.
void freeStack (STACK *stack)
Frees memory allocated for the entire stack.
Detailed Description
Header file for stack operations involving nodes containing a Latin square board.
This file contains function declarations for initializing and managing a stack of nodes, where each node holds a 2D array representing part of a Latin square.
Authors
Panagiotis Tsembekis
Rafael Tsekouronas
Bug:
No known bugs.
Typedef Documentation
NODE
typedef struct node NODE
STACK
typedef struct stack STACK
Function Documentation
freeNode()
void freeNode (NODE * node)
Frees memory allocated for a node.
Deallocates the 2D array within the node and then frees the node itself.
Parameters
node A pointer to the node to be freed.
{
    if (node != NULL)
    {
        if (node->square != NULL)
        {
            free2DArray(node->square, node->arraySize); // free 2D array
        }
        free(node); // free node itself
    }
}
References node::arraySize, free2DArray(), and node::square.
Referenced by freeStack(), and puzzleSolver().
freeStack()
void freeStack (STACK * stack)
Frees memory allocated for the entire stack.
Pops and frees each node in the stack, then frees the stack itself.
Parameters
stack A pointer to the stack to be freed.
{
    while (!isEmpty(stack))
    {
        NODE *node = pop(stack); // pop top node
        freeNode(node);          // free top node
    }
    free(stack);
}
References freeNode(), isEmpty(), and pop().
Referenced by main().
initNode()
int initNode (NODE ** newNode, int ** square, int row, int col, int size)
Initializes a new node with a Latin square board and position.
Allocates memory for a new node and its 2D array representing a board. Copies the content of the provided board array into the node.
Parameters
newNode A double pointer to the new node to be initialized.
board A 2D array representing the board to be copied into the node.
row The row position in the Latin square.
col The column position in the Latin square.
size The size of the Latin square.
Returns
EXIT_SUCCESS on successful initialization, EXIT_FAILURE otherwise.
{
    *newNode = (NODE *)malloc(sizeof(NODE));
    if (*newNode == NULL) // handle improper memory allocation
    {
        return EXIT_FAILURE;
    }
    // Assign values to `newNode`
    (*newNode)->row = row;
    (*newNode)->col = col;
    (*newNode)->arraySize = size;
    // Allocate memory for the 2D array
    (*newNode)->square = (int **)malloc(size * sizeof(int *));
    if ((*newNode)->square == NULL)
    { // handle improper memory allocation
        perror("Error: Memory allocation for new node's 2D array rows failed.\n");
        free(*newNode); // free previously allocated space for node
        *newNode = NULL;
        return EXIT_FAILURE;
    }
    // Allocate space for columns for 2D array of `newNode`
    for (int i = 0; i < size; i++)
    {
        (*newNode)->square[i] = (int *)malloc(size * sizeof(int));
        if ((*newNode)->square[i] == NULL) // handle improper memory allocation
        {
            perror("Error: Memory allocation for new node's 2D array columns failed.\n");
            // Free previously allocated space for 2D array and `node`
            free2DArray((*newNode)->square, i);
            free((*newNode)->square);
            free(*newNode); // free newNode itself
            *newNode = NULL;
            return EXIT_FAILURE;
        }
        // Copy each element in the row
        for (int j = 0; j < size; j++)
        {
            (*newNode)->square[i][j] = board[i][j];
        }
    }
    (*newNode)->next = NULL; // initialize the next pointer to NULL
    return EXIT_SUCCESS;
}
References free2DArray().
Referenced by attemptPlacement().
initStack()
int initStack (STACK ** stack)
Initializes the stack.
Allocates memory for a stack and initializes its top pointer and length.
Parameters
stack A double pointer to the stack to be initialized.
Returns
EXIT_SUCCESS on successful initialization, EXIT_FAILURE otherwise.
{
    *stack = (STACK *)malloc(1 * sizeof(STACK));
    if (stack == NULL) // handle improper memory allocation
    {
        return EXIT_FAILURE;
    }
    // Initialize stack's values
    (*stack)->top = NULL;
    (*stack)->length = 0;
    return EXIT_SUCCESS;
}
References stack::top.
Referenced by main().
isEmpty()
bool isEmpty (STACK * stack)
Checks if the stack is empty.
Determines if the stack contains any elements.
Parameters
stack A pointer to the stack.
Returns
true if the stack is empty, false otherwise.
{
    return (stack->length == 0); // if length = 0 => empty stack
}
References stack::length.
Referenced by freeStack(), printStack(), and puzzleSolver().
pop()
NODE * pop (STACK * stack)
Pops a node from the stack.
Removes and returns the node from the top of the stack.
Parameters
stack A pointer to the stack.
Returns
The popped node, or NULL if the stack is empty or NULL.
{
    if (stack == NULL || stack->length == 0) // handle edge case of empty/null stack
    {
        perror("Unable to pop from stack | Empty or NULL stack.\n");
        return NULL;
    }
    // Remove node at stack->top
    NODE *temp = stack->top;
    stack->top = temp->next;
    (stack->length)--;
    return temp;
}
References stack::length, and stack::top.
Referenced by freeStack(), and puzzleSolver().
printNode()
void printNode (NODE * node)
Prints the contents of a node.
Displays the 2D array of the given node with borders around each element. Negative values are shown within parentheses.
Parameters
node A pointer to the node to be printed.
{
    if (node == NULL) // handle edge case of null node
    {
        printf("Can't print node. Node is NULL!\n");
        return;
    }
    // Print top border for the node
    for (int i = 0; i < node->arraySize; i++)
    {
        printf("+-----");
    }
    printf("+\n");
    // Iterate over the 2D array and print each element with borders
    for (int i = 0; i < node->arraySize; i++)
    {
        for (int j = 0; j < node->arraySize; j++)
        {
            if (node->square[i][j] < 0)
            { // negative values printed inside parentheses
                printf("| (%d) ", -node->square[i][j]);
            }
            else
            { // normal values
                printf("|  %d  ", node->square[i][j]);
            }
        }
        printf("|\n"); // end the row
        // Print bottom border for the current row
        for (int k = 0; k < node->arraySize; k++)
        {
            printf("+-----");
        }
        printf("+\n");
    }
}
References node::arraySize, and node::square.
Referenced by attemptPlacement(), printStack(), and puzzleSolver().
printStack()
void printStack (STACK * stack, int size)
Prints the entire stack from top to bottom.
Iterates through each node in the stack and prints its contents.
Parameters
stack A pointer to the stack.
size The size of the 2D array in each node.
{
    if (isEmpty(stack))
    {
        printf("Stack is empty!\n");
        return;
    }
    NODE *current = stack->top; // start from top element
    printf("Stack elements (from top to bottom):\n");
    while (current != NULL)
    {
        printf("Node (row: %d, col: %d):\n", current->row, current->col);
        printNode(current); // print node's contents
        printf("\n"); // separate nodes with a blank line
        current = current->next;
    }
}
References isEmpty(), printNode(), and stack::top.
push()
int push (STACK * stack, NODE * newNode)
Pushes a node onto the stack.
Adds the specified node to the top of the stack.
Parameters
stack A pointer to the stack.
newNode The node to be pushed onto the stack.
Returns
EXIT_SUCCESS on successful push, EXIT_FAILURE if the stack or node is NULL.
{
    if (stack == NULL) // handle edge case of null stack
    {
        perror("Unable to push into stack | Stack is NULL.\n");
        return EXIT_FAILURE;
    }
    if (newNode == NULL) // handle edge case of null node passed in
    {
        perror("Unable to push into stack | newNode is NULL.\n");
    }
    // Add node to stack
    newNode->next = stack->top;
    stack->top = newNode;
    (stack->length)++;
    return EXIT_SUCCESS;
}
References stack::length, and stack::top.
Referenced by attemptPlacement().